# Use UTF-8 character encoding everywhere.
display-charset utf-8
utf8-strings

# When verifying a signature made from a subkey, require that the
# cross-certification "back signature" on the subkey is present and valid.
require-cross-certification

# Method references
personal-cipher-preferences AES256 AES192 AES
personal-digest-preferences SHA512 SHA384 SHA256
personal-compress-preferences ZLIB BZIP2 ZIP Uncompressed

# New keys config
default-preference-list SHA512 SHA384 SHA256 AES256 AES192 AES ZLIB BZIP2 ZIP Uncompressed
cert-digest-algo SHA512

# Symmatric ops
s2k-digest-algo SHA512
s2k-cipher-algo AES256
# Disable cahcing of passphrase for symmatrical ops
no-symkey-cache

# Don't leak comments or software version information
no-comments
no-emit-version

# Display full fingerprints
keyid-format 0xlong
with-fingerprint

# Other display preferences
list-options show-uid-validity
verify-options show-uid-validity

# Enable smart card
use-agent
