# Power down and ask PIN again after timout.
card-timeout 180  # 3 minutes

# Fix repeatedly prompting for an already-inserted YubiKey.
# It works by disabling CCID-support, so it does not clash with pcsc.
disable-ccid

