#!/usr/bin/env bash
ver=$(grep "^pkgver=" "./PKGBUILD" | sed "s/^pkgver=\(.*\)$/\1/" )
new=$(makepkg -f | grep Creating | sed "s/^.*\"\(.*\)\".*$/\1/g")

for pkg in "$new"; do
    match=$(find . -name "*${pkg}-${ver}*")
    >&2 echo "Adding ${match}"
    repo-add tdpeuter.db.tar.gz ${match}
done

rm tdpeuter.db tdpeuter.files
cp tdpeuter.db.tar.gz tdpeuter.db
cp tdpeuter.files.tar.gz tdpeuter.files

git add --all
git commit
git push

