# System actions
$mode_system = System (l)ock, (s)leep, (h)ibernate, (r)eboot, (Shift+s)hutdown
bind = Ctrl+Alt, Delete, submap, $mode_system
submap = $mode_system

bind =      , l, exec, $lock
bind =      , l, submap, reset
bind =      , s, exec, $lock, exec, systemctl suspend
bind =      , s, submap, reset
bind =      , h, exec, $lock, exec, systemctl hibernate
bind =      , h, submap, reset
bind =      , r, exec, systemctl reboot
bind = Shift, s, exec, systemctl poweroff -i

bind = Ctrl+Alt, Delete, submap, reset
bind =         , Escape, submap, reset
bind =         , Return, submap, reset

submap = reset

# Launcher
$mode_launcher = Launch (f)irefox, (t)hunderbird, (l)ogseq.
bind = $flag, O, submap, $mode_launcher
submap = $mode_launcher

bind = , F, exec,   firefox
bind = , F, submap, reset
bind = , L, exec,   logseq
bind = , L, submap, reset
bind = , T, exec,   thunderbird
bind = , T, submap, reset

bind = $flag, O, submap, reset
bind = , Escape, submap, reset
bind = , Return, submap, reset

submap = reset

