# Resizing
$mode_resize = Resize
bind = $flag, R, submap, $mode_resize
submap = $mode_resize

bind =      , $right, resizeactive,  10   0
bind =      , $up,    resizeactive,   0 -10
bind =      , $left,  resizeactive, -10   0
bind =      , $down,  resizeactive,   0  10

bind =      , Right , resizeactive,  10   0
bind =      , Up,     resizeactive,   0 -10
bind =      , Left,   resizeactive, -10   0
bind =      , Down,   resizeactive,   0  10

bind = Shift, $right, resizeactive,  50   0
bind = Shift, $up,    resizeactive,   0 -50
bind = Shift, $left,  resizeactive, -50   0
bind = Shift, $down,  resizeactive,   0  50

bind = Shift, Right , resizeactive,  50   0
bind = Shift, Up,     resizeactive,   0 -50
bind = Shift, Left,   resizeactive, -50   0
bind = Shift, Down,   resizeactive,   0  50

bind = $flag, $right, moveactive,    10   0
bind = $flag, $up,    moveactive,     0 -10
bind = $flag, $left,  moveactive,   -10   0
bind = $flag, $down,  moveactive,     0  10

bind = $flag, Right , moveactive,    10   0
bind = $flag, Up,     moveactive,     0 -10
bind = $flag, Left,   moveactive,   -10   0
bind = $flag, Down,   moveactive,     0  10

bind = $flag+Shift, $right, moveactive,  50   0
bind = $flag+Shift, $up,    moveactive,   0 -50
bind = $flag+Shift, $left,  moveactive, -50   0
bind = $flag+Shift, $down,  moveactive,   0  50

bind = $flag+Shift, Right , moveactive,  50   0
bind = $flag+Shift, Up,     moveactive,   0 -50
bind = $flag+Shift, Left,   moveactive, -50   0
bind = $flag+Shift, Down,   moveactive,   0  50

gesture = 3, swipe, move
gesture = 4, swipe, resize

bind = $flag,      R, submap, reset
bind =      , Escape, submap, reset
bind =      , Return, submap, reset

submap = reset

# System actions
$mode_system = System (l)ock, (s)leep, (h)ibernate, (r)eboot, (Shift+s)hutdown
bind = Ctrl+Alt, Delete, submap, $mode_system
submap = $mode_system

bind =      , l, exec, $lock
bind =      , l, submap, reset
bind =      , s, exec, $lock, exec, systemctl suspend
bind =      , s, submap, reset
bind =      , h, exec, $lock, exec, systemctl hibernate
bind =      , h, submap, reset
bind =      , r, exec, systemctl reboot
bind = Shift, s, exec, systemctl poweroff -i

bind = Ctrl+Alt, Delete, submap, reset
bind =         , Escape, submap, reset
bind =         , Return, submap, reset

submap = reset

# Launcher
$mode_launcher = Launch (f)irefox, (t)hunderbird, (l)ogseq.
bind = $flag, O, submap, $mode_launcher
submap = $mode_launcher

bind = , F, exec,   firefox
bind = , F, submap, reset
bind = , L, exec,   logseq
bind = , L, submap, reset
bind = , T, exec,   thunderbird
bind = , T, submap, reset

bind = $flag, O, submap, reset
bind = , Escape, submap, reset
bind = , Return, submap, reset

submap = reset

# Ignore (all) keybinds. Useful when working with Virtual Machines.
$mode_ignore=Ignore keybinds - Press Control+Alt+Insert to escape.
bind = Ctrl+Alt, Insert, submap, $mode_ignore
submap = $mode_ignore

bind = Ctrl+Alt, Insert, submap, reset

submap = reset
